# Generated by Django 3.2 on 2022-05-24 22:07

from django.db import migrations, models
import mag_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('mag_app', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Music', max_length=50, verbose_name=mag_app.models.Category),
        ),
    ]
