# Generated by Django 3.2 on 2022-05-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mag_app', '0004_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Music', 'Music'), ('Live', 'Live'), ('Review', 'Review'), ('Playlist', 'Playlist')], max_length=50),
        ),
    ]
