# Generated by Django 3.2 on 2022-05-26 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mag_app', '0007_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='Music', on_delete=django.db.models.deletion.CASCADE, to='mag_app.category'),
        ),
    ]
