# Generated by Django 3.2 on 2022-05-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mag_app', '0008_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='Music', max_length=50),
        ),
    ]
