# Generated by Django 3.2 on 2022-05-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mag_app', '0010_auto_20220530_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('playlist', 'playlist'), ('review', 'review'), ('music', 'music'), ('concert', 'concert')], default='music', max_length=200),
        ),
    ]
